### ISSUE TITLE
file sharing

### ISSUE THREAD

**Issue by veezo2007pk** [valarpirai/video-chat-app#3]
Can we allow file sharing between 2 peer?

**Comment by valarpirai** [comment]
Yes, we can share file between 2 peer. We have to use data connections for file transfer.
I have been using this Peer JS library for video communication - https://github.com/peers/peerjs.
Please go through the doc.

**Comment by veezo2007pk** [comment]
> Yes, we can share file between 2 peer. We have to use data connections for file transfer.
> I have been using this Peer JS library for video communication - https://github.com/peers/peerjs.
> Please go through the doc.

Sir can you guide me how can i implement file sharing in video chat app?  There is a code for file sharing which i uncomment it but nothing is showing in front end  for file sharing...
